import womenPerfumeImg from "@assets/generated_images/elegant_women's_perfume_bottle_with_floral_notes.png";
import menPerfumeImg from "@assets/generated_images/bold_men's_perfume_bottle_dark_glass.png";
import unisexPerfumeImg from "@assets/generated_images/unisex_minimalist_perfume_bottle.png";

export type Product = {
  id: string;
  name: string;
  price: number;
  category: "women" | "men" | "unisex";
  image: string;
  description?: string;
  tags?: string[];
};

export const products: Product[] = [
  // 🌸 PARFUMURI DAMĂ
  { id: "w-1", name: "Parfum inspirat de Jean Paul Gaultier Scandal Women", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Scandal Women Absolu, Eau de Parfum, 80 ml.jpg", },
  { id: "w-2", name: "Parfum inspirat de Jean Paul Gaultier Gaultier Divine", price: 215, category: "women", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Gaultier Divine, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "w-3", name: "Parfum inspirat de Tom Ford Private Blend Vanilla Sex", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Private Blend Vanilla Sex, Eau de Parfum, 100ml.jpg", },
  { id: "w-4", name: "Parfum inspirat de Jean Paul Gaultier La Belle Le Parfum", price: 215, category: "women", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier La Belle Le Parfum, Eau de Parfum, 100 ml.jpg", },
  { id: "w-5", name: "Parfum inspirat de Prada Paradoxe", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Prada Paradoxe EDP 100 ML TESTER.jpg", },
  { id: "w-6", name: "Parfum inspirat de Givenchy L’Interdit Rouge", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/GIVENCHY L’Interdit Rouge ,  Eau de Parfum, 80 ml.jpg", },
  { id: "w-7", name: "Parfum inspirat de Mugler Alien", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Mugler Alien, Eau de Parfum, 100ml.jpg", },
  { id: "w-8", name: "Parfum inspirat de Jean Paul Gaultier La Belle Paradise Garden", price: 215, category: "women", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier La Belle Paradise Garden, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "w-9", name: "Parfum inspirat de Dior J’adore", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/DIOR J'adore Parfum d’Eau, Eau de Parfum, 100ml.jpg", },
  { id: "w-10", name: "Parfum inspirat de Xerjoff Erba Pura", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Xerjoff Erba Pura, Eau de Parfum, 100ml.jpg", },
  { id: "w-11", name: "Parfum inspirat de Xerjoff Accento", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Xerjoff Accento, Eau de Parfum, 100ml.jpg", },
  { id: "w-12", name: "Parfum inspirat de Versace Crystal Noir", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/VERSACE Crystal Noir EDP 90 ML.jpg", },
  { id: "w-14", name: "Parfum inspirat de Chanel Chance", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Chanel Chance, Eau de Parfum, 100ml.jpg", },
  { id: "w-15", name: "Parfum inspirat de Sospiro Erba Pura", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Sospiro Erba Pura, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "w-16", name: "Parfum inspirat de Jean Paul Gaultier Scandal Women Absolu", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Scandal Women Absolu, Eau de Parfum, 80 ml.jpg", },
  { id: "w-17", name: "Parfum inspirat de Baccarat Rouge 540", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Baccarat Rouge 540, Eau de Parfum, 70 ml TESTER.jpg", },
  { id: "w-18", name: "Parfum inspirat de Tom Ford Noir Extreme", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir Extreme Eau de Parfum 100ml.jpg", },
  { id: "w-19", name: "Parfum inspirat de Tom Ford Black Orchid", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Black Orchid, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "w-20", name: "Parfum inspirat de Dior Hypnotic Poison", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Dior Hypnotic Poison, Eau de Parfum, 100 ml.jpg", },
  { id: "w-21", name: "Parfum inspirat de Carolina Herrera Good Girl", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Carolina Herrera GOOD GIRL Dazzling Garden 80 ml.jpg", },
  { id: "w-22", name: "Parfum inspirat de Armani Sì Intense", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Armani Emporio Stronger With You Intensely, Eau de Parfum, 100ml.jpg", },
  { id: "w-23", name: "Parfum inspirat de Tom Ford Rose Prick", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Rose Prick, Eau de Parfum, 100ml.jpg", },
  { id: "w-24", name: "Parfum inspirat de Tom Ford Vanille Fatale", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Vanille Fatale, Eau de Parfum, 100ml.jpg", },
  { id: "w-25", name: "Parfum inspirat de Xerjoff Opera", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Xerjoff Opera, Eau de Parfum, 100ml.jpg", },
  { id: "w-26", name: "Parfum inspirat de Tom Ford Lost Cherry", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Lost Cherry - EDP 100 ML TESTER.jpg", },
  { id: "w-27", name: "Parfum inspirat de Paco Rabanne Lady Million", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Paco Rabanne Lady Million 80 ml TESTER.jpg", },
  { id: "w-28", name: "Parfum inspirat de Lancôme La Vie Est Belle", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Lancôme La Vie Est Belle Intensément, Eau de Parfum, 75ml.jpg", },
  { id: "w-29", name: "Parfum inspirat de Dior Addict", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Dior Addict, Eau de Parfum, 100 ml.jpg", },
  { id: "w-30", name: "Parfum inspirat de Calvin Klein Euphoria", price: 159, category: "women", image: "/products/Parfumatica_Main_Photos/Calvin Klein Euphoria, Eau de Parfum, 100ml.jpg", },
  { id: "w-31", name: "Parfum inspirat de Givenchy L’Interdit", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/GIVENCHY L’INTERDIT – Apa de parfum , 80 ml.jpg", },
  { id: "w-32", name: "Parfum inspirat de Kilian Angel’s Share", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Kilian Angel's Share, Eau de Parfum, 50ml.jpg", },
  { id: "w-34", name: "Parfum inspirat de Chloé Nomade", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Chloé Nomade, Eau de Parfum, 75ml.jpg", },
  { id: "w-35", name: "Parfum inspirat de Amouage Interlude Women", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Amouage Interlude Dama, Eau de Parfum, 100ml.jpg", },
  { id: "w-36", name: "Parfum inspirat de Tom Ford Bitter Peach", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Bitter Peach, Eau de Parfum 100ml.jpg", },
  { id: "w-38", name: "Parfum inspirat de Giardini di Toscana Bianco Latte", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Giardini di Toscana Bianco Latte, Eau de Parfum, 100ml.jpg", },
  { id: "w-39", name: "Parfum inspirat de Tom Ford Cherry Smoke", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Cherry Smoke, Eau de Parfum, 100ml.jpg", },
  { id: "w-40", name: "Parfum inspirat de Tom Ford Tuscan Leather", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Tuscan Leather, Eau de Parfum, 100ml.jpg", },
  { id: "w-42", name: "Parfum inspirat de Chanel Coco Noir", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Chanel Coco Noir, Eau de Parfum, 100ml.jpg", },
  { id: "w-43", name: "Parfum inspirat de Carolina Herrera Very Good Girl", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Carolina Herrera Very Good Girl, Eau de Parfum, 80ml.jpg", },
  { id: "w-44", name: "Parfum inspirat de BVLGARI Jasmin Noir", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/BVLGARI Splendida Bvlgari Jasmin Noir, Eau de Parfum, 100ml.jpg", },
  { id: "w-45", name: "Parfum inspirat de Hermes Eau Des Merveilles", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Hermes Eau Des Merveilles 100 ml.jpg", },
  { id: "w-46", name: "Parfum inspirat de Tom Ford Mandarino di Amalfi", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Mandarino di Amalfi, Eau de Parfum 100ml.jpg", },
  { id: "w-47", name: "Parfum inspirat de Tom Ford Oud Wood", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Oud Wood – Eau de Parfum, 100ml.jpg", },
  { id: "w-48", name: "Parfum inspirat de Xerjoff Erba Gold", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Xerjoff Erba Gold, Eau de Parfum, 100ml.jpg", },
  { id: "w-49", name: "Parfum inspirat de Armani Code Femme", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Armani Code Femme EDP 100 ML.jpg", },
  { id: "w-50", name: "Parfum inspirat de Armani My Way", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Armani My Way Intense, Eau de Parfum, 90ml.jpg", },
  { id: "w-51", name: "Parfum inspirat de YSL Black Opium", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Yves Saint Laurent Black Opium Extreme, Eau de Parfum, 90ml.jpg", },
  { id: "w-52", name: "Parfum inspirat de Lancôme La Vie Est Belle L’Elixir", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Lancôme La Vie Est Belle L'Elixir, Eau de Parfum, 75ml.jpg", },
  { id: "w-54", name: "Parfum inspirat de Hugo Boss The Scent For Her", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Hugo Boss BOSS The Scent For Her, Eau de Parfum, 100ml.jpg", },
  { id: "w-55", name: "Parfum inspirat de Gisada Ambassador Women", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Gisada Ambassador Women, Eau de Parfum, 100ml.jpg", },
  { id: "w-56", name: "Parfum inspirat de Parfums de Marly Delina", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Royal Essence Parfums De Marly Delina, Eau de Parfum, 75ml.jpg", },
  { id: "w-57", name: "Parfum inspirat de Tom Ford Soleil Brûlant", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Orchid Soleil, Eau de Parfum, 100ml.jpg", },
  { id: "w-58", name: "Parfum inspirat de Tom Ford Costa Azzura", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Costa Azzura, Eau de Parfum, 100 ml.jpg", },
  { id: "w-59", name: "Parfum inspirat de Sospiro Accento", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Sospiro Accento, Eau de Parfum, 100ml.jpg", },
  { id: "w-60", name: "Parfum inspirat de Xerjoff Laylati", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Xerjoff Laylati, Eau de Parfum, 100ml.jpg", },
  { id: "w-61", name: "Parfum inspirat de Versace Bright Crystal", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/VERSACE Bright Crystal EDT 100 ML TESTER.jpg", },
  { id: "w-62", name: "Parfum inspirat de Paco Rabanne Fame Intense", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Paco Rabanne Fame Intense, Eau de Parfum, 80ml.jpg", },
  { id: "w-64", name: "Parfum inspirat de Gucci Bloom", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Gucci Bloom, Eau de Parfum, 100ml.jpg", },
  { id: "w-65", name: "Parfum inspirat de Dior J'adore Parfum d’Eau", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/DIOR J'adore Parfum d’Eau, Eau de Parfum, 100ml.jpg", },
  { id: "w-66", name: "Parfum inspirat de Chanel Coco Mademoiselle", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Chanel Coco Mademoiselle L’Eau Privée, Eau de Parfum, 100ml.jpg", },
  { id: "w-67", name: "Parfum inspirat de Carolina Herrera Good Girl Blush", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Carolina Herrera Good Girl Blush, Eau de Parfum, 100ml.jpg", },
  { id: "w-68", name: "Parfum inspirat de Tom Ford Neroli Portofino", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Neroli Portofino – Eau de Parfum, 100ml.jpg", },
  { id: "w-69", name: "Parfum inspirat de Tom Ford Velvet Orchid", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Velvet Orchid – Eau de Parfum, 100ml.jpg", },
  { id: "w-70", name: "Parfum inspirat de Tom Ford Noir", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir Extreme Eau de Parfum 100ml.jpg", },
  { id: "w-71", name: "Parfum inspirat de Hugo Boss The Scent Elixir", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Hugo Boss BOSS The Scent Elixir for him , Eau de parfum, 100 ml.jpg", },
  { id: "w-72", name: "Parfum inspirat de YSL Libre L’Absolu Platine", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Yves Saint Laurent Libre L’Absolu Platine, Eau de Parfum, 90ml.jpg", },
  { id: "w-73", name: "Parfum inspirat de Givenchy L’Interdit Intense", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/GIVENCHY L’Interdit Intense, Eau de Parfum, 80ml.jpg", },
  { id: "w-74", name: "Parfum inspirat de YSL Black Opium Extreme", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Yves Saint Laurent Black Opium Extreme, Eau de Parfum, 90ml.jpg", },
  { id: "w-75", name: "Parfum inspirat de YSL Mon Paris", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Yves Saint Laurent Mon Paris, Eau de Parfum, 90ml.jpg", },
  { id: "w-76", name: "Parfum inspirat de Sospiro Laylati", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Sospiro Laylati, Eau de Parfum, 100ml.jpg", },
  { id: "w-77", name: "Parfum inspirat de Armani Because It’s You", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Emporio Armani Because It’s You, Eau de Parfum, 100ml.jpg", },
  { id: "w-78", name: "Parfum inspirat de Sospiro Erba Gold", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Sospiro Erba Gold, Eau de Parfum, 100ml.jpg", },
  { id: "w-80", name: "Parfum inspirat de Paco Rabanne Fame Blooming Pink", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Paco Rabanne Fame Blooming Pink, Eau de Parfum, 80ml.jpg", },
  { id: "w-81", name: "Parfum inspirat de Lancôme La Vie Est Belle Intense", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Lancôme La Vie Est Belle Intensément, Eau de Parfum, 75ml.jpg", },
  { id: "w-82", name: "Parfum inspirat de Kayali Vanilla Candy Rock Sugar 42", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Kayali Vanilla Candy Rock Sugar 42, Eau de Parfum, 100ml.jpg", },
  { id: "w-83", name: "Parfum inspirat de Kayali Vanilla 28", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/KAYALI VANILLA 28, Eau de Parfum, 100ml.jpg", },
  { id: "w-84", name: "Parfum inspirat de Guerlain La Petite Robe Noire", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/GUERLAIN La Petite Robe Noire, Eau de Parfum, 100ml.jpg", },
  { id: "w-85", name: "Parfum inspirat de Dior Miss Dior Chérie", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Dior Miss Dior Chérie, Eau de Parfum, 100 ml.jpg", },
  { id: "w-86", name: "Parfum inspirat de Chanel N°5", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Chanel N°5, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "w-87", name: "Parfum inspirat de Chanel Coco Mademoiselle L’Eau Privée", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Chanel Coco Mademoiselle L’Eau Privée, Eau de Parfum, 100ml.jpg", },
  { id: "w-88", name: "Parfum inspirat de Carolina Herrera Good Girl Gold Fantasy", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Carolina Herrera Good Girl Gold Fantasy, Eau de Parfum, 80ml.jpg", },
  { id: "w-89", name: "Parfum inspirat de Carolina Herrera 212 VIP Rosé", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/CAROLINA HERRERA 212 VIP Rosé.jpg", },
  { id: "w-90", name: "Parfum inspirat de Burberry My Burberry", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Burberry My Burberry Blush, Eau de Parfum, 100 ml.jpg", },
  { id: "w-91", name: "Parfum inspirat de Burberry My Burberry Blush", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Burberry My Burberry Blush, Eau de Parfum, 100 ml.jpg", },
  { id: "w-92", name: "Parfum inspirat de Burberry Goddess", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Burberry Goddess, Eau de Parfum, 100ml.jpg", },
  { id: "w-93", name: "Parfum inspirat de Armani Sì", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Armani Sì Intense, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "w-94", name: "Parfum inspirat de Armani Sì Passione", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Armani Sì Passione, Eau de Parfum, 100 ml.jpg", },
  { id: "w-95", name: "Parfum inspirat de Armani My Way Intense", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Armani My Way Intense, Eau de Parfum, 90ml.jpg", },
  { id: "w-96", name: "Parfum inspirat de Armani Code Absolu", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Giorgio Armani Code Absolu Apa de parfum, 75 ml.jpg", },
  { id: "w-97", name: "Parfum inspirat de Montale Intense Cafe", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Montale Intense Cafe, Apa de Parfum, Unisex - 100ml.jpg", },
  { id: "w-98", name: "Parfum inspirat de Marc Jacobs Decadence", price: 229, category: "women", image: "/products/Parfumatica_Main_Photos/Marc Jacobs Decadence EDP 100 ML.jpg", },
  { id: "w-99", name: "Parfum inspirat de Carolina Herrera Good Girl Dazzling Garden", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Carolina Herrera GOOD GIRL Dazzling Garden 80 ml.jpg", },
  { id: "w-100", name: "Parfum inspirat de Tiziana Terenzi Kirke", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tiziana Terenzi Kirke, Extrait de Parfum 100ml.jpg", },
  { id: "w-101", name: "Parfum inspirat de YSL Supreme Bouquet", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Yves Saint Laurent Le Vestiaire Des Parfums Supreme Bouquet, Eau de Parfum, 100 ml.jpg", },
  { id: "w-102", name: "Parfum inspirat de Paco Rabanne Olympéa Parfum", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Paco Rabanne 1 Million  100 ML TESTER.jpg", },
  { id: "w-103", name: "Parfum inspirat de Tom Ford Café Rose", price: 199, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Café Rose, Eau de Parfum, 100 ml.jpg", },
  { id: "w-104", name: "Parfum inspirat de Prada Candy Florale", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Prada Candy Florale, Eau de Parfum, 80ml.jpg", },
  { id: "w-105", name: "Parfum inspirat de Elie Saab Le Parfum", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Elie Saab Le Parfum, Eau de Parfum, 90ml.jpg", },
  { id: "w-106", name: "Parfum inspirat de Tom Ford Noir de Noir", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir de Noir, Eau de Parfum, 100ml.jpg", },
  { id: "w-107", name: "Parfum inspirat de Tom Ford Orchid Soleil", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Tom Ford Orchid Soleil, Eau de Parfum, 100ml.jpg", },
  { id: "w-108", name: "Parfum inspirat de Paco Rabanne Fame", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Paco Rabanne Fame Blooming Pink, Eau de Parfum, 80ml.jpg", },
  { id: "w-109", name: "Parfum inspirat de Dolce&Gabbana The One", price: 159, category: "women", image: "/products/Parfumatica_Main_Photos/Dolce&Gabbana The One, Eau de Parfum, 75ml TESTER.jpg", },
  { id: "w-110", name: "Parfum inspirat de Dolce&Gabbana Devotion", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Dolce&Gabbana Devotion, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "w-112", name: "Parfum inspirat de Narciso Rodriguez For Her", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Narciso Rodriguez For Her EDT - 100 ML TESTER.jpg", },
  { id: "w-114", name: "Parfum inspirat de Guerlain Mon Guerlain", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Guerlain Mon Guerlain, Eau de Parfum, 100 ml.jpg", },
  { id: "w-115", name: "Parfum inspirat de Gucci Guilty Femme", price: 179, category: "women", image: "/products/Parfumatica_Main_Photos/Gucci Guilty Femme, Eau de Toilette, 75 ml.jpg", },
  { id: "w-116", name: "Parfum inspirat de Chloé Love Story", price: 169, category: "women", image: "/products/Parfumatica_Main_Photos/Chloé Love Story, Eau de Parfum, 75ml.jpg", },
  { id: "w-117", name: "Parfum inspirat de Carolina Herrera Good Girl Velvet Fatale", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Carolina Herrera Good Girl Velvet Fatale, Eau de Parfum, 100ml.jpg", },
  { id: "w-118", name: "Parfum inspirat de Carolina Herrera Good Girl Fantastic Pink", price: 189, category: "women", image: "/products/Parfumatica_Main_Photos/Carolina Herrera Good Girl Fantastic Pink, Eau de Parfum, 100ml.jpg", },
  { id: "w-119", name: "Parfum inspirat de Burberry Hero", price: 159, category: "women", image: "/products/Parfumatica_Main_Photos/Burberry Hero, Eau de Toilette, 100ml.jpg", },

  // 👑 PARFUMURI BĂRBAȚI
  { id: "m-1", name: "Parfum inspirat de Jean Paul Gaultier Le Male Elixir", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Le Male Elixir, Eau de Parfum, 100ml.jpg", },
  { id: "m-2", name: "Parfum inspirat de Armani Stronger With You Intensely", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Armani Emporio Stronger With You Intensely, Eau de Parfum, 100ml.jpg", },
  { id: "m-3", name: "Parfum inspirat de Armani Stronger With You Absolutely", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Armani Emporio Stronger With You Absolutely, Eau de Parfum, 100ml.jpg", },
  { id: "m-4", name: "Parfum inspirat de Jean Paul Gaultier Le Male Le Parfum", price: 215, category: "men", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Le Male Le Parfum, Eau de Parfum, 100 ml.jpg", },
  { id: "m-5", name: "Parfum inspirat de Dior Sauvage", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/DIOR Sauvage Elixir, Eau de Parfum, 60 ml.jpg", },
  { id: "m-6", name: "Parfum inspirat de Jean Paul Gaultier Scandal Pour Homme Le Parfum", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Scandal Pour Homme Le Parfum, Eau de Parfum, 80ml.jpg", },
  { id: "m-7", name: "Parfum inspirat de Jean Paul Gaultier Scandal Pour Homme", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Scandal Pour Homme , Eau de Parfum, 100 ml TESTER.jpg", },
  { id: "m-8", name: "Parfum inspirat de Armani Stronger With You Parfum", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Armani Emporio Stronger With You Absolutely, Eau de Parfum, 100ml.jpg", },
  { id: "m-9", name: "Parfum inspirat de Tom Ford Private Blend Vanilla Sex", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Private Blend Vanilla Sex, Eau de Parfum, 100ml.jpg", },
  { id: "m-10", name: "Parfum inspirat de Jean Paul Gaultier Scandal Pour Homme Absolu", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Scandal Pour Homme Absolu, Eau de Parfum, 100 ml.jpg", },
  { id: "m-11", name: "Parfum inspirat de Dior Sauvage Elixir", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/DIOR Sauvage Elixir, Eau de Parfum, 60 ml.jpg", },
  { id: "m-12", name: "Parfum inspirat de Louis Vuitton Ombre Nomade", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Louis Vuitton Ombre Nomade 100 ml TESTER.jpg", },
  { id: "m-13", name: "Parfum inspirat de Dior Homme Intense", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Dior Homme Intense, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "m-14", name: "Parfum inspirat de Versace Eros", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/VERSACE Eros , Eau de Parfum, 100 ml TESTER.jpg", },
  { id: "m-15", name: "Parfum inspirat de YSL MYSLF", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Yves Saint Laurent MYSLF, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "m-16", name: "Parfum inspirat de Tom Ford Ombre Leather", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Ombre Leather Parfum, 100ml.jpg", },
  { id: "m-17", name: "Parfum inspirat de Dior Fahrenheit", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Dior Fahrenheit, Eau de Parfum, 100 ml.jpg", },
  { id: "m-18", name: "Parfum inspirat de Armani Acqua di Giò Profumo", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Giorgio Armani Acqua di Giò Profumo, Eau de Parfum, 100 ml.jpg", },
  { id: "m-19", name: "Parfum inspirat de Xerjoff Erba Pura", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Xerjoff Erba Pura, Eau de Parfum, 100ml.jpg", },
  { id: "m-20", name: "Parfum inspirat de Xerjoff Accento", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Xerjoff Accento, Eau de Parfum, 100ml.jpg", },
  { id: "m-21", name: "Parfum inspirat de Versace Eros Flame", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Versace Eros Flame Eau de Parfum 100 ML TESTER.jpg", },
  { id: "m-22", name: "Parfum inspirat de Boss The Scent", price: 159, category: "men", image: "/products/Parfumatica_Main_Photos/Boss The Scent, Apă de Toaletă, 100 ml.jpg", },
  { id: "m-23", name: "Parfum inspirat de Sospiro Erba Pura", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Sospiro Erba Pura, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "m-24", name: "Parfum inspirat de BVLGARI Man In Black", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/BVLGARI Bvlgari Man In Black, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "m-26", name: "Parfum inspirat de Armani Stronger With You Oud", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Armani Emporio Stronger With You Oud, Eau de Parfum, 100ml.jpg", },
  { id: "m-27", name: "Parfum inspirat de Armani Code", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Armani Code Femme EDP 100 ML.jpg", },
  { id: "m-28", name: "Parfum inspirat de Tom Ford Noir Extreme", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir Extreme Eau de Parfum 100ml.jpg", },
  { id: "m-29", name: "Parfum inspirat de Tom Ford Black Orchid", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Black Orchid, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "m-30", name: "Parfum inspirat de Armani Stronger With You Leather", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Armani Emporio Stronger With You Leather, Eau de Parfum, 100ml.jpg", },
  { id: "m-31", name: "Parfum inspirat de Versace Eros Energy", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/VERSACE Eros Energy ,  Eau de Parfum, 100 ml.jpg", },
  { id: "m-32", name: "Parfum inspirat de Tom Ford Rose Prick", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Rose Prick, Eau de Parfum, 100ml.jpg", },
  { id: "m-33", name: "Parfum inspirat de Tom Ford Vanille Fatale", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Vanille Fatale, Eau de Parfum, 100ml.jpg", },
  { id: "m-34", name: "Parfum inspirat de Xerjoff Opera", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Xerjoff Opera, Eau de Parfum, 100ml.jpg", },
  { id: "m-36", name: "Parfum inspirat de Tom Ford Lost Cherry", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Lost Cherry - EDP 100 ML TESTER.jpg", },
  { id: "m-37", name: "Parfum inspirat de Creed Aventus", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Creed Aventus, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "m-38", name: "Parfum inspirat de Paco Rabanne Invictus Legend", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Paco Rabanne Invictus Legend EDP 100 ML.jpg", },
  { id: "m-39", name: "Parfum inspirat de Prada Luna Rossa Black", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Prada Luna Rossa Black, Eau de Parfum, 100ml.jpg", },
  { id: "m-42", name: "Parfum inspirat de Hugo Boss The Scent Elixir for Him", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Hugo Boss BOSS The Scent Elixir for him , Eau de parfum, 100 ml.jpg", },
  { id: "m-43", name: "Parfum inspirat de Tom Ford Bitter Peach", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Bitter Peach, Eau de Parfum 100ml.jpg", },
  { id: "m-44", name: "Parfum inspirat de Tom Ford Cherry Smoke", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Cherry Smoke, Eau de Parfum, 100ml.jpg", },
  { id: "m-45", name: "Parfum inspirat de Tom Ford Tuscan Leather", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Tuscan Leather, Eau de Parfum, 100ml.jpg", },
  { id: "m-46", name: "Parfum inspirat de Jean Paul Gaultier Ultra Male", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Le Male Ultra Male, Eau de Toilette, 125 ml.jpg", },
  { id: "m-47", name: "Parfum inspirat de Jean Paul Gaultier Le Male", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Jean Paul Gaultier Le Male Elixir, Eau de Parfum, 100ml.jpg", },
  { id: "m-48", name: "Parfum inspirat de Armani Stronger With You Amber", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Armani Emporio Stronger With You Amber, Eau de Parfum, 100 ml.jpg", },
  { id: "m-49", name: "Parfum inspirat de BVLGARI Aqva Pour Homme", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Bvlgari Aqva Pour Homme - EDT 100 ML.jpg", },
  { id: "m-50", name: "Parfum inspirat de Tom Ford Mandarino di Amalfi", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Mandarino di Amalfi, Eau de Parfum 100ml.jpg", },
  { id: "m-51", name: "Parfum inspirat de Tom Ford Oud Wood", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Oud Wood – Eau de Parfum, 100ml.jpg", },
  { id: "m-52", name: "Parfum inspirat de Carolina Herrera Bad Boy", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Carolina Herrera Bad Boy, Eau de Toilette, 80ml.jpg", },
  { id: "m-53", name: "Parfum inspirat de Xerjoff Erba Gold", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Xerjoff Erba Gold, Eau de Parfum, 100ml.jpg", },
  { id: "m-54", name: "Parfum inspirat de Chanel Allure Homme Sport", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Chanel Allure Homme Sport EDT 100 ML TESTER.jpg", },
  { id: "m-55", name: "Parfum inspirat de Paco Rabanne 1 Million Royal", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Paco Rabanne 1 Million Royal 100 ML.jpg", },
  { id: "m-56", name: "Parfum inspirat de Givenchy Gentleman Society Extrême", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/GIVENCHY Gentleman Society Extrême, Eau de Parfum, 100ml.jpg", },
  { id: "m-57", name: "Parfum inspirat de Givenchy Gentleman", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/GIVENCHY Gentleman , Eau de Parfum, 100ml TESTER.jpg", },
  { id: "m-58", name: "Parfum inspirat de Armani Stronger With You EDT", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Armani Emporio Stronger With You Absolutely, Eau de Parfum, 100ml.jpg", },
  { id: "m-59", name: "Parfum inspirat de Valentino Uomo", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Valentino Uomo EDT 100ml for Men.jpg", },
  { id: "m-60", name: "Parfum inspirat de BVLGARI Man Wood Essence", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Bvlgari Man Wood Essence 100 ml.jpg", },
  { id: "m-62", name: "Parfum inspirat de Prada Luna Rossa Carbon", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Prada Luna Rossa Carbon, Eau de Toilette, 100ml.jpg", },
  { id: "m-63", name: "Parfum inspirat de Tom Ford Soleil Brûlant", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Orchid Soleil, Eau de Parfum, 100ml.jpg", },
  { id: "m-64", name: "Parfum inspirat de Tom Ford Costa Azzura", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Costa Azzura, Eau de Parfum, 100 ml.jpg", },
  { id: "m-65", name: "Parfum inspirat de Carolina Herrera 212 Heroes", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Carolina Herrera 212 Heroes, Eau de Parfum, 90ml.jpg", },
  { id: "m-66", name: "Parfum inspirat de Sospiro Accento", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Sospiro Accento, Eau de Parfum, 100ml.jpg", },
  { id: "m-67", name: "Parfum inspirat de Xerjoff Laylati", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Xerjoff Laylati, Eau de Parfum, 100ml.jpg", },
  { id: "m-68", name: "Parfum inspirat de Paco Rabanne Invictus Victory", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Paco Rabanne Invictus Victory EDP 100 ML.jpg", },
  { id: "m-69", name: "Parfum inspirat de Paco Rabanne 1 Million Privé", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Paco Rabanne 1 Million PRIVE 100 ML.jpg", },
  { id: "m-70", name: "Parfum inspirat de Kilian Back To Black", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Kilian Back To Black Aphrodisiac, Eau de Parfum, 50ml.jpg", },
  { id: "m-71", name: "Parfum inspirat de Hugo Boss Bottled", price: 159, category: "men", image: "/products/Parfumatica_Main_Photos/Hugo Boss Boss Bottled, Eau de Toilette, 100 ml.jpg", },
  { id: "m-72", name: "Parfum inspirat de Armani Acqua di Giò Absolu", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Giorgio Armani Acqua di Giò Absolu, Eau de Parfum, 100 ml.jpg", },
  { id: "m-73", name: "Parfum inspirat de Azzaro Wanted", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Azzaro Wanted, Eau de Toilette, 100ml.jpg", },
  { id: "m-75", name: "Parfum inspirat de Tom Ford Neroli Portofino", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Neroli Portofino – Eau de Parfum, 100ml.jpg", },
  { id: "m-76", name: "Parfum inspirat de Tom Ford Velvet Orchid", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Velvet Orchid – Eau de Parfum, 100ml.jpg", },
  { id: "m-77", name: "Parfum inspirat de Tom Ford Noir", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir Extreme Eau de Parfum 100ml.jpg", },
  { id: "m-80", name: "Parfum inspirat de Sospiro Laylati", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Sospiro Laylati, Eau de Parfum, 100ml.jpg", },
  { id: "m-81", name: "Parfum inspirat de Sospiro Erba Gold", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Sospiro Erba Gold, Eau de Parfum, 100ml.jpg", },
  { id: "m-82", name: "Parfum inspirat de Viktor & Rolf Spicebomb", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Viktor & Rolf Spicebomb, Eau de Toilette, 90ml.jpg", },
  { id: "m-83", name: "Parfum inspirat de Paco Rabanne Phantom", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Paco Rabanne Phantom , Eau de Toilette, 100ml TESTER.jpg", },
  { id: "m-84", name: "Parfum inspirat de Kilian Black Phantom", price: 229, category: "men", image: "/products/Parfumatica_Main_Photos/Kilian Black Phantom, Eau de Parfum, 50ml.jpg", },
  { id: "m-85", name: "Parfum inspirat de Armani Acqua di Giò Profondo", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Giorgo Armani Acqua di Giò Profondo, Eau de Parfum, 100ml.jpg", },
  { id: "m-86", name: "Parfum inspirat de Montale Intense Cafe", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Montale Intense Cafe, Apa de Parfum, Unisex - 100ml.jpg", },
  { id: "m-87", name: "Parfum inspirat de Tom Ford Café Rose", price: 199, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Café Rose, Eau de Parfum, 100 ml.jpg", },
  { id: "m-88", name: "Parfum inspirat de Paco Rabanne Phantom Legion", price: 179, category: "men", image: "/products/Parfumatica_Main_Photos/Paco Rabanne Phantom Legion Collector, Eau de Toilette, 100ml.jpg", },
  { id: "m-89", name: "Parfum inspirat de Tom Ford Noir de Noir", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir de Noir, Eau de Parfum, 100ml.jpg", },
  { id: "m-90", name: "Parfum inspirat de Tom Ford Orchid Soleil", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/Tom Ford Orchid Soleil, Eau de Parfum, 100ml.jpg", },
  { id: "m-91", name: "Parfum inspirat de Hugo Boss The Scent Le Parfum", price: 169, category: "men", image: "/products/Parfumatica_Main_Photos/Hugo Boss BOSS The Scent Elixir for him , Eau de parfum, 100 ml.jpg", },
  { id: "m-92", name: "Parfum inspirat de Givenchy Gentleman Intense", price: 189, category: "men", image: "/products/Parfumatica_Main_Photos/GIVENCHY Gentleman Intense, Eau de Toilette, 100ml.jpg", },
  { id: "m-93", name: "Parfum inspirat de Dolce&Gabbana Light Blue Pour Homme", price: 159, category: "men", image: "/products/Parfumatica_Main_Photos/Dolce&Gabbana Light Blue Pour Homme 100 ml.jpg", },
  { id: "m-94", name: "Parfum inspirat de Burberry Hero", price: 159, category: "men", image: "/products/Parfumatica_Main_Photos/Burberry Hero, Eau de Toilette, 100ml.jpg", },

  // ⚪ PARFUMURI UNISEX
  { id: "u-1", name: "Parfum inspirat de Tom Ford Private Blend Vanilla Sex", price: 189, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Private Blend Vanilla Sex, Eau de Parfum, 100ml.jpg", },
  { id: "u-2", name: "Parfum inspirat de Xerjoff Erba Pura", price: 229, category: "unisex", image: "/products/Parfumatica_Main_Photos/Xerjoff Erba Pura, Eau de Parfum, 100ml.jpg", },
  { id: "u-3", name: "Parfum inspirat de Xerjoff Accento", price: 229, category: "unisex", image: "/products/Parfumatica_Main_Photos/Xerjoff Accento, Eau de Parfum, 100ml.jpg", },
  { id: "u-4", name: "Parfum inspirat de Sospiro Erba Pura", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Sospiro Erba Pura, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "u-5", name: "Parfum inspirat de Tom Ford Noir Extreme", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir Extreme Eau de Parfum 100ml.jpg", },
  { id: "u-6", name: "Parfum inspirat de Tom Ford Black Orchid", price: 189, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Black Orchid, Eau de Parfum, 100ml TESTER.jpg", },
  { id: "u-7", name: "Parfum inspirat de Tom Ford Rose Prick", price: 179, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Rose Prick, Eau de Parfum, 100ml.jpg", },
  { id: "u-8", name: "Parfum inspirat de Tom Ford Vanille Fatale", price: 179, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Vanille Fatale, Eau de Parfum, 100ml.jpg", },
  { id: "u-9", name: "Parfum inspirat de Tom Ford Lost Cherry", price: 189, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Lost Cherry - EDP 100 ML TESTER.jpg", },
  { id: "u-10", name: "Parfum inspirat de Xerjoff Opera", price: 229, category: "unisex", image: "/products/Parfumatica_Main_Photos/Xerjoff Opera, Eau de Parfum, 100ml.jpg", },
  { id: "u-11", name: "Parfum inspirat de Tom Ford Bitter Peach", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Bitter Peach, Eau de Parfum 100ml.jpg", },
  { id: "u-12", name: "Parfum inspirat de Tom Ford Cherry Smoke", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Cherry Smoke, Eau de Parfum, 100ml.jpg", },
  { id: "u-13", name: "Parfum inspirat de Tom Ford Tuscan Leather", price: 189, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Tuscan Leather, Eau de Parfum, 100ml.jpg", },
  { id: "u-14", name: "Parfum inspirat de Tom Ford Mandarino di Amalfi", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Mandarino di Amalfi, Eau de Parfum 100ml.jpg", },
  { id: "u-15", name: "Parfum inspirat de Tom Ford Oud Wood", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Oud Wood – Eau de Parfum, 100ml.jpg", },
  { id: "u-16", name: "Parfum inspirat de Xerjoff Erba Gold", price: 229, category: "unisex", image: "/products/Parfumatica_Main_Photos/Xerjoff Erba Gold, Eau de Parfum, 100ml.jpg", },
  { id: "u-17", name: "Parfum inspirat de Tom Ford Soleil Brûlant", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Orchid Soleil, Eau de Parfum, 100ml.jpg", },
  { id: "u-18", name: "Parfum inspirat de Tom Ford Costa Azzura", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Costa Azzura, Eau de Parfum, 100 ml.jpg", },
  { id: "u-19", name: "Parfum inspirat de Sospiro Accento", price: 229, category: "unisex", image: "/products/Parfumatica_Main_Photos/Sospiro Accento, Eau de Parfum, 100ml.jpg", },
  { id: "u-20", name: "Parfum inspirat de Xerjoff Laylati", price: 229, category: "unisex", image: "/products/Parfumatica_Main_Photos/Xerjoff Laylati, Eau de Parfum, 100ml.jpg", },
  { id: "u-21", name: "Parfum inspirat de Tom Ford Neroli Portofino", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Neroli Portofino – Eau de Parfum, 100ml.jpg", },
  { id: "u-22", name: "Parfum inspirat de Tom Ford Velvet Orchid", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Velvet Orchid – Eau de Parfum, 100ml.jpg", },
  { id: "u-23", name: "Parfum inspirat de Tom Ford Noir", price: 189, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir Extreme Eau de Parfum 100ml.jpg", },
  { id: "u-24", name: "Parfum inspirat de Sospiro Laylati", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Sospiro Laylati, Eau de Parfum, 100ml.jpg", },
  { id: "u-25", name: "Parfum inspirat de Sospiro Erba Gold", price: 229, category: "unisex", image: "/products/Parfumatica_Main_Photos/Sospiro Erba Gold, Eau de Parfum, 100ml.jpg", },
  { id: "u-26", name: "Parfum inspirat de Montale Intense Cafe", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Montale Intense Cafe, Apa de Parfum, Unisex - 100ml.jpg", },
  { id: "u-27", name: "Parfum inspirat de Tom Ford Café Rose", price: 199, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Café Rose, Eau de Parfum, 100 ml.jpg", },
  { id: "u-28", name: "Parfum inspirat de Tom Ford Noir de Noir", price: 189, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Noir de Noir, Eau de Parfum, 100ml.jpg", },
  { id: "u-29", name: "Parfum inspirat de Tom Ford Orchid Soleil", price: 189, category: "unisex", image: "/products/Parfumatica_Main_Photos/Tom Ford Orchid Soleil, Eau de Parfum, 100ml.jpg", },
];

export const getProductsByCategory = (category: string) => products.filter(p => p.category === category);
export const getProductById = (id: string) => products.find(p => p.id === id);
