import womenPerfumeImg from "@assets/generated_images/elegant_women's_perfume_bottle_with_floral_notes.png";
import menPerfumeImg from "@assets/generated_images/bold_men's_perfume_bottle_dark_glass.png";
import unisexPerfumeImg from "@assets/generated_images/unisex_minimalist_perfume_bottle.png";

export type Product = {
  id: string;
  name: string;
  price: number;
  oldPrice: number;
  category: "women" | "men" | "unisex";
  image: string;
  description?: string;
  tags?: string[];
};

export const products: Product[] = [
  // 🌸 PARFUMURI DAMĂ
  { id: "w-1", name: "Jean Paul Gaultier Scandal Women", price: 179, oldPrice: 370, category: "women", image: womenPerfumeImg },
  { id: "w-2", name: "Jean Paul Gaultier Gaultier Divine", price: 215, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-3", name: "Tom Ford Private Blend Vanilla Sex", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-4", name: "Jean Paul Gaultier La Belle Le Parfum", price: 215, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-5", name: "Prada Paradoxe", price: 179, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-6", name: "Givenchy L’Interdit Rouge", price: 189, oldPrice: 370, category: "women", image: womenPerfumeImg },
  { id: "w-7", name: "Mugler Alien", price: 179, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-8", name: "Jean Paul Gaultier La Belle Paradise Garden", price: 215, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-9", name: "Dior J’adore", price: 179, oldPrice: 420, category: "women", image: womenPerfumeImg },
  { id: "w-10", name: "Xerjoff Erba Pura", price: 229, oldPrice: 980, category: "women", image: womenPerfumeImg },
  { id: "w-11", name: "Xerjoff Accento", price: 229, oldPrice: 450, category: "women", image: womenPerfumeImg },
  { id: "w-12", name: "Versace Crystal Noir", price: 179, oldPrice: 330, category: "women", image: womenPerfumeImg },
  { id: "w-13", name: "Lancôme Trésor La Nuit", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-14", name: "Chanel Chance", price: 189, oldPrice: 765, category: "women", image: womenPerfumeImg },
  { id: "w-15", name: "Sospiro Erba Pura", price: 199, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-16", name: "Jean Paul Gaultier Scandal Women Absolu", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-17", name: "Baccarat Rouge 540", price: 229, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-18", name: "Tom Ford Noir Extreme", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-19", name: "Tom Ford Black Orchid", price: 189, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-20", name: "Dior Hypnotic Poison", price: 179, oldPrice: 340, category: "women", image: womenPerfumeImg },
  { id: "w-21", name: "Carolina Herrera Good Girl", price: 179, oldPrice: 659, category: "women", image: womenPerfumeImg },
  { id: "w-22", name: "Armani Sì Intense", price: 179, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-23", name: "Tom Ford Rose Prick", price: 179, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-24", name: "Tom Ford Vanille Fatale", price: 179, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-25", name: "Xerjoff Opera", price: 229, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-26", name: "Tom Ford Lost Cherry", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-27", name: "Paco Rabanne Lady Million", price: 169, oldPrice: 330, category: "women", image: womenPerfumeImg },
  { id: "w-28", name: "Lancôme La Vie Est Belle", price: 179, oldPrice: 370, category: "women", image: womenPerfumeImg },
  { id: "w-29", name: "Dior Addict", price: 179, oldPrice: 310, category: "women", image: womenPerfumeImg },
  { id: "w-30", name: "Calvin Klein Euphoria", price: 159, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-31", name: "Givenchy L’Interdit", price: 179, oldPrice: 370, category: "women", image: womenPerfumeImg },
  { id: "w-32", name: "Kilian Angel’s Share", price: 229, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-33", name: "YSL Libre", price: 179, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-34", name: "Chloé Nomade", price: 179, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-35", name: "Amouage Interlude Women", price: 229, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-36", name: "Tom Ford Bitter Peach", price: 199, oldPrice: 390, category: "women", image: womenPerfumeImg },
  { id: "w-37", name: "YSL Libre Le Parfum", price: 189, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-38", name: "Giardini di Toscana Bianco Latte", price: 179, oldPrice: 340, category: "women", image: womenPerfumeImg },
  { id: "w-39", name: "Tom Ford Cherry Smoke", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-40", name: "Tom Ford Tuscan Leather", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-41", name: "Lancôme Poême", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-42", name: "Chanel Coco Noir", price: 179, oldPrice: 390, category: "women", image: womenPerfumeImg },
  { id: "w-43", name: "Carolina Herrera Very Good Girl", price: 189, oldPrice: 370, category: "women", image: womenPerfumeImg },
  { id: "w-44", name: "BVLGARI Jasmin Noir", price: 189, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-45", name: "Hermes Eau Des Merveilles", price: 199, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-46", name: "Tom Ford Mandarino di Amalfi", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-47", name: "Tom Ford Oud Wood", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-48", name: "Xerjoff Erba Gold", price: 229, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-49", name: "Armani Code Femme", price: 169, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-50", name: "Armani My Way", price: 169, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-51", name: "YSL Black Opium", price: 179, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-52", name: "Lancôme La Vie Est Belle L’Elixir", price: 199, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-53", name: "Chloé EDP", price: 179, oldPrice: 310, category: "women", image: womenPerfumeImg },
  { id: "w-54", name: "Hugo Boss The Scent For Her", price: 169, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-55", name: "Gisada Ambassador Women", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-56", name: "Parfums de Marly Delina", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-57", name: "Tom Ford Soleil Brûlant", price: 199, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-58", name: "Tom Ford Costa Azzura", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-59", name: "Sospiro Accento", price: 229, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-60", name: "Xerjoff Laylati", price: 229, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-61", name: "Versace Bright Crystal", price: 169, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-62", name: "Paco Rabanne Fame Intense", price: 179, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-63", name: "Lancôme Idôle L’Intense", price: 169, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-64", name: "Gucci Bloom", price: 169, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-65", name: "Dior J'adore Parfum d’Eau", price: 169, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-66", name: "Chanel Coco Mademoiselle", price: 189, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-67", name: "Carolina Herrera Good Girl Blush", price: 189, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-68", name: "Tom Ford Neroli Portofino", price: 199, oldPrice: 390, category: "women", image: womenPerfumeImg },
  { id: "w-69", name: "Tom Ford Velvet Orchid", price: 199, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-70", name: "Tom Ford Noir", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-71", name: "Hugo Boss The Scent Elixir", price: 179, oldPrice: 330, category: "women", image: womenPerfumeImg },
  { id: "w-72", name: "YSL Libre L’Absolu Platine", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-73", name: "Givenchy L’Interdit Intense", price: 179, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-74", name: "YSL Black Opium Extreme", price: 189, oldPrice: 370, category: "women", image: womenPerfumeImg },
  { id: "w-75", name: "YSL Mon Paris", price: 179, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-76", name: "Sospiro Laylati", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-77", name: "Armani Because It’s You", price: 179, oldPrice: 390, category: "women", image: womenPerfumeImg },
  { id: "w-78", name: "Sospiro Erba Gold", price: 229, oldPrice: 990, category: "women", image: womenPerfumeImg },
  { id: "w-79", name: "YSL Black Opium Le Parfum", price: 189, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-80", name: "Paco Rabanne Fame Blooming Pink", price: 189, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-81", name: "Lancôme La Vie Est Belle Intense", price: 189, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-82", name: "Kayali Vanilla Candy Rock Sugar 42", price: 189, oldPrice: 330, category: "women", image: womenPerfumeImg },
  { id: "w-83", name: "Kayali Vanilla 28", price: 189, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-84", name: "Guerlain La Petite Robe Noire", price: 179, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-85", name: "Dior Miss Dior Chérie", price: 189, oldPrice: 450, category: "women", image: womenPerfumeImg },
  { id: "w-86", name: "Chanel N°5", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-87", name: "Chanel Coco Mademoiselle L’Eau Privée", price: 189, oldPrice: 310, category: "women", image: womenPerfumeImg },
  { id: "w-88", name: "Carolina Herrera Good Girl Gold Fantasy", price: 189, oldPrice: 340, category: "women", image: womenPerfumeImg },
  { id: "w-89", name: "Carolina Herrera 212 VIP Rosé", price: 169, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-90", name: "Burberry My Burberry", price: 179, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-91", name: "Burberry My Burberry Blush", price: 179, oldPrice: 340, category: "women", image: womenPerfumeImg },
  { id: "w-92", name: "Burberry Goddess", price: 179, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-93", name: "Armani Sì", price: 169, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-94", name: "Armani Sì Passione", price: 179, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-95", name: "Armani My Way Intense", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-96", name: "Armani Code Absolu", price: 199, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-97", name: "Montale Intense Cafe", price: 199, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-98", name: "Marc Jacobs Decadence", price: 229, oldPrice: 500, category: "women", image: womenPerfumeImg },
  { id: "w-99", name: "Carolina Herrera Good Girl Dazzling Garden", price: 189, oldPrice: 360, category: "women", image: womenPerfumeImg },
  { id: "w-100", name: "Tiziana Terenzi Kirke", price: 199, oldPrice: 390, category: "women", image: womenPerfumeImg },
  { id: "w-101", name: "YSL Supreme Bouquet", price: 189, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-102", name: "Paco Rabanne Olympéa Parfum", price: 189, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-103", name: "Tom Ford Café Rose", price: 199, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-104", name: "Prada Candy Florale", price: 169, oldPrice: 330, category: "women", image: womenPerfumeImg },
  { id: "w-105", name: "Elie Saab Le Parfum", price: 169, oldPrice: 340, category: "women", image: womenPerfumeImg },
  { id: "w-106", name: "Tom Ford Noir de Noir", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-107", name: "Tom Ford Orchid Soleil", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-108", name: "Paco Rabanne Fame", price: 169, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-109", name: "Dolce&Gabbana The One", price: 159, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-110", name: "Dolce&Gabbana Devotion", price: 169, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-111", name: "YSL Manifesto", price: 179, oldPrice: 763, category: "women", image: womenPerfumeImg },
  { id: "w-112", name: "Narciso Rodriguez For Her", price: 169, oldPrice: 250, category: "women", image: womenPerfumeImg },
  { id: "w-113", name: "Hermès Twilly", price: 159, oldPrice: 300, category: "women", image: womenPerfumeImg },
  { id: "w-114", name: "Guerlain Mon Guerlain", price: 179, oldPrice: 350, category: "women", image: womenPerfumeImg },
  { id: "w-115", name: "Gucci Guilty Femme", price: 179, oldPrice: 320, category: "women", image: womenPerfumeImg },
  { id: "w-116", name: "Chloé Love Story", price: 169, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-117", name: "Carolina Herrera Good Girl Velvet Fatale", price: 189, oldPrice: 380, category: "women", image: womenPerfumeImg },
  { id: "w-118", name: "Carolina Herrera Good Girl Fantastic Pink", price: 189, oldPrice: 400, category: "women", image: womenPerfumeImg },
  { id: "w-119", name: "Burberry Hero", price: 159, oldPrice: 379, category: "women", image: womenPerfumeImg },

  // 👑 PARFUMURI BĂRBAȚI
  { id: "m-1", name: "Jean Paul Gaultier Le Male Elixir", price: 229, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-2", name: "Armani Stronger With You Intensely", price: 179, oldPrice: 370, category: "men", image: menPerfumeImg },
  { id: "m-3", name: "Armani Stronger With You Absolutely", price: 179, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-4", name: "Jean Paul Gaultier Le Male Le Parfum", price: 215, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-5", name: "Dior Sauvage", price: 179, oldPrice: 370, category: "men", image: menPerfumeImg },
  { id: "m-6", name: "Jean Paul Gaultier Scandal Pour Homme Le Parfum", price: 189, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-7", name: "Jean Paul Gaultier Scandal Pour Homme", price: 179, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-8", name: "Armani Stronger With You Parfum", price: 179, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-9", name: "Tom Ford Private Blend Vanilla Sex", price: 189, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-10", name: "Jean Paul Gaultier Scandal Pour Homme Absolu", price: 189, oldPrice: 390, category: "men", image: menPerfumeImg },
  { id: "m-11", name: "Dior Sauvage Elixir", price: 189, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-12", name: "Louis Vuitton Ombre Nomade", price: 229, oldPrice: 450, category: "men", image: menPerfumeImg },
  { id: "m-13", name: "Dior Homme Intense", price: 189, oldPrice: 370, category: "men", image: menPerfumeImg },
  { id: "m-14", name: "Versace Eros", price: 169, oldPrice: 300, category: "men", image: menPerfumeImg },
  { id: "m-15", name: "YSL MYSLF", price: 179, oldPrice: 330, category: "men", image: menPerfumeImg },
  { id: "m-16", name: "Tom Ford Ombre Leather", price: 189, oldPrice: 500, category: "men", image: menPerfumeImg },
  { id: "m-17", name: "Dior Fahrenheit", price: 169, oldPrice: 300, category: "men", image: menPerfumeImg },
  { id: "m-18", name: "Armani Acqua di Giò Profumo", price: 179, oldPrice: 370, category: "men", image: menPerfumeImg },
  { id: "m-19", name: "Xerjoff Erba Pura", price: 229, oldPrice: 980, category: "men", image: menPerfumeImg },
  { id: "m-20", name: "Xerjoff Accento", price: 229, oldPrice: 450, category: "men", image: menPerfumeImg },
  { id: "m-21", name: "Versace Eros Flame", price: 179, oldPrice: 320, category: "men", image: menPerfumeImg },
  { id: "m-22", name: "Boss The Scent", price: 159, oldPrice: 300, category: "men", image: menPerfumeImg },
  { id: "m-23", name: "Sospiro Erba Pura", price: 199, oldPrice: 500, category: "men", image: menPerfumeImg },
  { id: "m-24", name: "BVLGARI Man In Black", price: 169, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-25", name: "Armani Acqua di Giò EDT", price: 159, oldPrice: 290, category: "men", image: menPerfumeImg },
  { id: "m-26", name: "Armani Stronger With You Oud", price: 189, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-27", name: "Armani Code", price: 169, oldPrice: 300, category: "men", image: menPerfumeImg },
  { id: "m-28", name: "Tom Ford Noir Extreme", price: 199, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-29", name: "Tom Ford Black Orchid", price: 189, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-30", name: "Armani Stronger With You Leather", price: 189, oldPrice: 390, category: "men", image: menPerfumeImg },
  { id: "m-31", name: "Versace Eros Energy", price: 179, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-32", name: "Tom Ford Rose Prick", price: 179, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-33", name: "Tom Ford Vanille Fatale", price: 179, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-34", name: "Xerjoff Opera", price: 229, oldPrice: 500, category: "men", image: menPerfumeImg },
  { id: "m-35", name: "Hermès Terre d’Hermès", price: 189, oldPrice: 300, category: "men", image: menPerfumeImg },
  { id: "m-36", name: "Tom Ford Lost Cherry", price: 189, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-37", name: "Creed Aventus", price: 189, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-38", name: "Paco Rabanne Invictus Legend", price: 179, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-39", name: "Prada Luna Rossa Black", price: 179, oldPrice: 340, category: "men", image: menPerfumeImg },
  { id: "m-40", name: "YSL Y Man", price: 179, oldPrice: 330, category: "men", image: menPerfumeImg },
  { id: "m-41", name: "Dolce&Gabbana K", price: 189, oldPrice: 340, category: "men", image: menPerfumeImg },
  { id: "m-42", name: "Hugo Boss The Scent Elixir for Him", price: 179, oldPrice: 310, category: "men", image: menPerfumeImg },
  { id: "m-43", name: "Tom Ford Bitter Peach", price: 199, oldPrice: 390, category: "men", image: menPerfumeImg },
  { id: "m-44", name: "Tom Ford Cherry Smoke", price: 199, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-45", name: "Tom Ford Tuscan Leather", price: 189, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-46", name: "Jean Paul Gaultier Ultra Male", price: 199, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-47", name: "Jean Paul Gaultier Le Male", price: 199, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-48", name: "Armani Stronger With You Amber", price: 199, oldPrice: 410, category: "men", image: menPerfumeImg },
  { id: "m-49", name: "BVLGARI Aqva Pour Homme", price: 169, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-50", name: "Tom Ford Mandarino di Amalfi", price: 199, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-51", name: "Tom Ford Oud Wood", price: 199, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-52", name: "Carolina Herrera Bad Boy", price: 179, oldPrice: 330, category: "men", image: menPerfumeImg },
  { id: "m-53", name: "Xerjoff Erba Gold", price: 229, oldPrice: 500, category: "men", image: menPerfumeImg },
  { id: "m-54", name: "Chanel Allure Homme Sport", price: 179, oldPrice: 450, category: "men", image: menPerfumeImg },
  { id: "m-55", name: "Paco Rabanne 1 Million Royal", price: 179, oldPrice: 330, category: "men", image: menPerfumeImg },
  { id: "m-56", name: "Givenchy Gentleman Society Extrême", price: 189, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-57", name: "Givenchy Gentleman", price: 179, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-58", name: "Armani Stronger With You EDT", price: 169, oldPrice: 330, category: "men", image: menPerfumeImg },
  { id: "m-59", name: "Valentino Uomo", price: 169, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-60", name: "BVLGARI Man Wood Essence", price: 169, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-61", name: "YSL La Nuit de L’Homme", price: 179, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-62", name: "Prada Luna Rossa Carbon", price: 179, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-63", name: "Tom Ford Soleil Brûlant", price: 199, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-64", name: "Tom Ford Costa Azzura", price: 199, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-65", name: "Carolina Herrera 212 Heroes", price: 179, oldPrice: 310, category: "men", image: menPerfumeImg },
  { id: "m-66", name: "Sospiro Accento", price: 229, oldPrice: 500, category: "men", image: menPerfumeImg },
  { id: "m-67", name: "Xerjoff Laylati", price: 229, oldPrice: 500, category: "men", image: menPerfumeImg },
  { id: "m-68", name: "Paco Rabanne Invictus Victory", price: 179, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-69", name: "Paco Rabanne 1 Million Privé", price: 189, oldPrice: 320, category: "men", image: menPerfumeImg },
  { id: "m-70", name: "Kilian Back To Black", price: 229, oldPrice: 500, category: "men", image: menPerfumeImg },
  { id: "m-71", name: "Hugo Boss Bottled", price: 159, oldPrice: 300, category: "men", image: menPerfumeImg },
  { id: "m-72", name: "Armani Acqua di Giò Absolu", price: 179, oldPrice: 390, category: "men", image: menPerfumeImg },
  { id: "m-73", name: "Azzaro Wanted", price: 169, oldPrice: 391, category: "men", image: menPerfumeImg },
  { id: "m-74", name: "Layton Parfums de Marly", price: 199, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-75", name: "Tom Ford Neroli Portofino", price: 199, oldPrice: 390, category: "men", image: menPerfumeImg },
  { id: "m-76", name: "Tom Ford Velvet Orchid", price: 199, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-77", name: "Tom Ford Noir", price: 189, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-78", name: "YSL La Nuit de L’Homme Le Parfum", price: 169, oldPrice: 370, category: "men", image: menPerfumeImg },
  { id: "m-79", name: "YSL Y Man EDT", price: 159, oldPrice: 300, category: "men", image: menPerfumeImg },
  { id: "m-80", name: "Sospiro Laylati", price: 199, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-81", name: "Sospiro Erba Gold", price: 229, oldPrice: 990, category: "men", image: menPerfumeImg },
  { id: "m-82", name: "Viktor & Rolf Spicebomb", price: 169, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-83", name: "Paco Rabanne Phantom", price: 169, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-84", name: "Kilian Black Phantom", price: 229, oldPrice: 500, category: "men", image: menPerfumeImg },
  { id: "m-85", name: "Armani Acqua di Giò Profondo", price: 179, oldPrice: 310, category: "men", image: menPerfumeImg },
  { id: "m-86", name: "Montale Intense Cafe", price: 199, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-87", name: "Tom Ford Café Rose", price: 199, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-88", name: "Paco Rabanne Phantom Legion", price: 179, oldPrice: 330, category: "men", image: menPerfumeImg },
  { id: "m-89", name: "Tom Ford Noir de Noir", price: 189, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-90", name: "Tom Ford Orchid Soleil", price: 189, oldPrice: 400, category: "men", image: menPerfumeImg },
  { id: "m-91", name: "Hugo Boss The Scent Le Parfum", price: 169, oldPrice: 350, category: "men", image: menPerfumeImg },
  { id: "m-92", name: "Givenchy Gentleman Intense", price: 189, oldPrice: 380, category: "men", image: menPerfumeImg },
  { id: "m-93", name: "Dolce&Gabbana Light Blue Pour Homme", price: 159, oldPrice: 300, category: "men", image: menPerfumeImg },
  { id: "m-94", name: "Burberry Hero", price: 159, oldPrice: 379, category: "men", image: menPerfumeImg },

  // ⚪ PARFUMURI UNISEX
  { id: "u-1", name: "Tom Ford Private Blend Vanilla Sex", price: 189, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-2", name: "Xerjoff Erba Pura", price: 229, oldPrice: 980, category: "unisex", image: unisexPerfumeImg },
  { id: "u-3", name: "Xerjoff Accento", price: 229, oldPrice: 450, category: "unisex", image: unisexPerfumeImg },
  { id: "u-4", name: "Sospiro Erba Pura", price: 199, oldPrice: 500, category: "unisex", image: unisexPerfumeImg },
  { id: "u-5", name: "Tom Ford Noir Extreme", price: 199, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-6", name: "Tom Ford Black Orchid", price: 189, oldPrice: 350, category: "unisex", image: unisexPerfumeImg },
  { id: "u-7", name: "Tom Ford Rose Prick", price: 179, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-8", name: "Tom Ford Vanille Fatale", price: 179, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-9", name: "Tom Ford Lost Cherry", price: 189, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-10", name: "Xerjoff Opera", price: 229, oldPrice: 500, category: "unisex", image: unisexPerfumeImg },
  { id: "u-11", name: "Tom Ford Bitter Peach", price: 199, oldPrice: 390, category: "unisex", image: unisexPerfumeImg },
  { id: "u-12", name: "Tom Ford Cherry Smoke", price: 199, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-13", name: "Tom Ford Tuscan Leather", price: 189, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-14", name: "Tom Ford Mandarino di Amalfi", price: 199, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-15", name: "Tom Ford Oud Wood", price: 199, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-16", name: "Xerjoff Erba Gold", price: 229, oldPrice: 500, category: "unisex", image: unisexPerfumeImg },
  { id: "u-17", name: "Tom Ford Soleil Brûlant", price: 199, oldPrice: 350, category: "unisex", image: unisexPerfumeImg },
  { id: "u-18", name: "Tom Ford Costa Azzura", price: 199, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-19", name: "Sospiro Accento", price: 229, oldPrice: 500, category: "unisex", image: unisexPerfumeImg },
  { id: "u-20", name: "Xerjoff Laylati", price: 229, oldPrice: 500, category: "unisex", image: unisexPerfumeImg },
  { id: "u-21", name: "Tom Ford Neroli Portofino", price: 199, oldPrice: 390, category: "unisex", image: unisexPerfumeImg },
  { id: "u-22", name: "Tom Ford Velvet Orchid", price: 199, oldPrice: 380, category: "unisex", image: unisexPerfumeImg },
  { id: "u-23", name: "Tom Ford Noir", price: 189, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-24", name: "Sospiro Laylati", price: 199, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-25", name: "Sospiro Erba Gold", price: 229, oldPrice: 990, category: "unisex", image: unisexPerfumeImg },
  { id: "u-26", name: "Montale Intense Cafe", price: 199, oldPrice: 380, category: "unisex", image: unisexPerfumeImg },
  { id: "u-27", name: "Tom Ford Café Rose", price: 199, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-28", name: "Tom Ford Noir de Noir", price: 189, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
  { id: "u-29", name: "Tom Ford Orchid Soleil", price: 189, oldPrice: 400, category: "unisex", image: unisexPerfumeImg },
];

export const getProductsByCategory = (category: string) => products.filter(p => p.category === category);
export const getProductById = (id: string) => products.find(p => p.id === id);
